version: "3.3"
services:
        sqldb:
                container_name: sqldb
                image: mysql
                restart: unless-stopped
                environment:
                        MYSQL_ROOT_PASSWORD: 1234
                volumes:
                        - /mysqldata:/var/lib/mysql
                ports:
                        - 3306:3306

        spring_app:
                container_name: voyage
                image: image1
                restart: on-failure
                ports:
                        - "8089:8089"
                depends_on:
                        - sqldb
