version: "3.3"
services:
        jenkins:
                image: jenkinsci/blueocean:latest
                container_name: jenkins2
                ports:
                        - 8080:8080
                volumes:
                        - ./jenkins:/var/jenkins_home
                restart: on-failure

